config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

def create
  @book = Book.new(book_params)
  if @book.save
    redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully created.'
  else
    @books = Book.all
    render 'index'
  end
end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to "/books"  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <% if @book.errors.any? %>
    <h2 class="warning"><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul class="warning">
      <% @book.errors.full_messages.each do |massage| %>
      <li><%= massage %></li>
      <% end %>
    </ul>
  <% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to 'Show', book_path(@book) %>
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>New book</h1>

<%= form_with model:@book, url:'/books', local:true do |f| %>
  <% if @book.errors.any? %>
    <h2 class="warning"><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul class="warning">
      <% @book.errors.full_messages.each do |massage| %>
      <li><%= massage %></li>
      <% end %>
    </ul>
  <% end %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<p class="notice"><%= notice %></p>


<table>
    <tr>
        <th>title:</th>
        <td><%= @book.title %></td>
    </tr>
    <tr>
        <th>body:</th>
        <td><%= @book.body %></td>
    </tr>
</table>

<%= link_to 'Edit', edit_book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や<br>
<br>
印象を共有し交換することができます</p>

<div class="btn"><%= link_to "Start",books_path %></div>